# Generated by Django 4.1.6 on 2023-05-01 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item name or title', max_length=256)),
                ('description', models.TextField()),
                ('amount', models.IntegerField(default=0)),
                ('target', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'On Going'), (2, 'Canceled'), (3, 'Finish'), (4, 'Realocated')], default=0)),
                ('currency', models.PositiveSmallIntegerField(choices=[(0, 'IDR')], default=0)),
                ('repeat', models.PositiveSmallIntegerField(choices=[(0, 'Once a day'), (1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Yearly')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
