# Generated by Django 4.1.6 on 2023-05-01 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item name or title', max_length=256)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('target', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(default=(0, 'Created'))),
                ('currency', models.PositiveSmallIntegerField(default=0, verbose_name=[(0, 'IDR')])),
                ('repeat', models.PositiveSmallIntegerField(choices=[(0, 'Once a day'), (1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Yearly')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
