# Generated by Django 4.1.6 on 2023-02-13 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='wallet.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('IDR', 'Indonesia Rupiah')], default='Indonesia Rupiah', max_length=256),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Expenses', 'Expenses'), ('Income', 'Income')], max_length=256),
        ),
    ]
