# Generated by Django 4.1.6 on 2023-07-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_account_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transfer',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
