# Generated by Django 4.1.6 on 2023-07-12 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_account_initial_transfer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.SmallIntegerField(choices=[('0', 'Expenses'), ('1', 'Income')], default='0'),
        ),
    ]
